### ISSUE TITLE
Running the application from scratch, get the error is TypeError: Failed to execute 'createComputePipeline' on 'GPUDevice'

### ISSUE THREAD

**Issue by suoken** [webonnx/wonnx-wasm-example#1]
Following the instructions for how to build the application I get the following console error: 

<img width="1920" alt="image" src="https://github.com/webonnx/wonnx-wasm-example/assets/22568107/07bca843-e0c4-4a09-a63b-faad49d22881">

`Uncaught (in promise) TypeError: Failed to execute 'createComputePipeline' on 'GPUDevice': Failed to read the 'layout' property from 'GPUPipelineDescriptorBase': Required member is undefined.`

Running in Chrome Version 113.0.5672.63 (Official Build) (x86_64) and Chrome Version 115.0.5760.0 (Official Build) canary (x86_64). 

OS: macOS Monterey 12.6.5

Not sure what's going on with that error

**Comment by pixelspark** [comment]
Hm, can you check the version of the wonnx package you are using? Should be 0.5.0 (the 0.2.4 version is not expected to work anymore following changes in the WGSL/WebGPU spec). Also verify that the following demo works in your browser: https://t-shaped.nl/wp-content/public/wonnx/ (requires a webcam).

**Comment by suoken** [comment]
Ah I see the problem. The example is out of date and also doesn't use squeezenet model as seen in the website. I made a pull request to reflect what's on that website https://github.com/webonnx/wonnx-wasm-example/pull/2

**Comment by pixelspark** [comment]
Great! Let’s continue in #2
