### ISSUE TITLE
onnx IR error

### ISSUE THREAD

**Issue by Jwy-jump** [webonnx/wonnx-wasm-example#3]
IR error: output node for output 309 not found
`    console.log("Initialized", { modelBytes, initResult, Session});
    console.log("debug1")
    // Start inference session
    const session = await Session.fromBytes(modelBytes);
    console.log("debug2")`

const session = await Session.fromBytes(modelBytes); error : output node for output 309 not found

**Comment by pixelspark** [comment]
This report does not have sufficient information to deduce the issue. If you want us to have a look, post at least the model file (preferably a minimal model that produces the issue).
