### ISSUE TITLE
provide / host online demo

### ISSUE THREAD

**Issue by Abdull** [webonnx/wonnx-wasm-example#4]
is there an online instance of this example?

**Comment by pixelspark** [comment]
https://dl.pixelspark.nl/wonnx/

**Comment by Abdull** [comment]
wow, this is a great demo! So the demo is a realtime object detection application, using the computer's video source / webcam, and it guesses immediately what is being presented.


I'm using `google-chrome-unstable --enable-unsafe-webgpu --enable-features=Vulkan` (*Version 124.0.6315.2 (Official Build) dev (64-bit)*) under Debian 12 on a *Framework Laptop 13 DIY Edition (AMD Ryzen™ 7040 Series)* with 16 GiB RAM, shared-memory onboard graphics.
